/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        accent: "var(--accent-primary, #00F0FF)",
        accentSec: "var(--accent-secondary, #C778DD)",
        accentTertiary: "var(--accent-tertiary, #00FF66)",
        void: "#0a0a0a",
        surface: "#121212",
        surfaceAlt: "#1a1a1a",
        primary: "#0a0a0a",
        secondary: "var(--accent-primary, #00F0FF)",
        brutalCyan: "#00F0FF",
        brutalMagenta: "#C778DD",
        brutalGreen: "#00FF66",
        brutalOrange: "#FF6B00",
        brutalPink: "#FF3366",
        brutalWhite: "#FFFFFF",
        brutalBorder: "#262626",
      },
      fontFamily: {
        mono: ['"JetBrains Mono"', '"Space Mono"', "monospace"],
        heading: ['"Space Grotesk"', "sans-serif"],
        sans: ['"Space Grotesk"', "sans-serif"],
        serif: ['"Playfair Display"', '"Instrument Serif"', "Georgia", "serif"],
        editorial: ['"Playfair Display"', '"Instrument Serif"', "Georgia", "serif"],
        retro: ['"VT323"', '"Courier New"', "monospace"],
        pixel: ['"Silkscreen"', '"VT323"', "monospace"],
      },
      boxShadow: {
        'brutal-sm': '2px 2px 0px 0px #ffffff',
        'brutal': '4px 4px 0px 0px #ffffff',
        'brutal-lg': '6px 6px 0px 0px #ffffff',
        'brutal-accent': '4px 4px 0px 0px var(--accent-primary, #00F0FF)',
        'brutal-accent-lg': '6px 6px 0px 0px var(--accent-primary, #00F0FF)',
        'brutal-sec': '4px 4px 0px 0px var(--accent-secondary, #C778DD)',
        'brutal-cyan': '4px 4px 0px 0px #00F0FF',
        'brutal-cyan-lg': '6px 6px 0px 0px #00F0FF',
        'brutal-magenta': '4px 4px 0px 0px #C778DD',
        'brutal-green': '4px 4px 0px 0px #00FF66',
        'brutal-pink': '4px 4px 0px 0px #FF3366',
        'brutal-black': '4px 4px 0px 0px #000000',
        'brutal-black-lg': '6px 6px 0px 0px #000000',
      },
      animation: {
        'ticker': 'ticker 25s linear infinite',
        'zen-float': 'zenFloat 6s ease-in-out infinite',
        'glow-breathe': 'glowBreathe 4s ease-in-out infinite',
        'crt-flicker': 'crtFlicker 0.15s infinite',
        'dos-blink': 'dosBlink 1s step-start infinite',
        'radar-sweep': 'radarSweep 3s linear infinite',
        'shimmer-slide': 'shimmerSlide 3s ease-in-out infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'border-beam': 'borderBeam 4s linear infinite',
        'spin-slow': 'spin 12s linear infinite',
        'reverse-spin': 'reverseSpin 8s linear infinite',
        'cinematic-zoom': 'cinematicZoom 1.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      keyframes: {
        ticker: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        reverseSpin: {
          '0%': { transform: 'rotate(360deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        cinematicZoom: {
          '0%': { transform: 'scale(0.85)', opacity: '0' },
          '40%': { transform: 'scale(1)', opacity: '1' },
          '80%': { transform: 'scale(1.03)', opacity: '1' },
          '100%': { transform: 'scale(1.1)', opacity: '0' },
        },
        zenFloat: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        glowBreathe: {
          '0%, 100%': { opacity: '0.4', filter: 'blur(20px)' },
          '50%': { opacity: '0.8', filter: 'blur(30px)' },
        },
        crtFlicker: {
          '0%': { opacity: '0.98' },
          '50%': { opacity: '1' },
          '100%': { opacity: '0.96' },
        },
        dosBlink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        radarSweep: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(1000%)' },
        },
        shimmerSlide: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        borderBeam: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
    },
  },
  plugins: [],
};
